### ISSUE TITLE
file lifespan tracking 관련 질문드립니다.

### ISSUE THREAD

**Issue by hyunW3** [ESOS-Lab/AndroTrace#1]
안녕하세요 AndroTrace논문을 읽고 이해를 위해 코드를 보고 있는 대학생입니다.현재 androTrace/kernel/nexus5_3.4.0 베이스로 코드를 보고 있는 중입니다. 시간이 많이 지났지만 답변해주시면 감사하겠습니다.
논문 4.4 File Lifespan 마지막 줄에 언급에서, unlink system call을 수정하여서 file의 life span을 계산하고, trace을 collect했다고 언급되어있는데요.
이와 관련하여 궁금한 것이 두 가지가 있습니다.
1. 따로 unlink system call을 수정한 것을 찾지 못했습니다. 어디서 확인할 수 있을까요? 
 
2. androtrace/androtrace.c 파일에서 androtrace_add_filels(400번째 줄) 함수에서 466번째 줄을 보면 생성된 time과 삭제되었을 때 time의 차이를 이용해서 계산하는 식이 주석 처리되어 있는데, 다른 함수에서도 lifespan을 계산하는 것을 찾지 못했습니다. 
header에서 delete time이 저장되어있고, create time은 442번째 줄에서 inode에서 가져와서 log 변수(filels 구조체)에 저장되어있는 것은 확인했습니다. 변수명을 따라가봐도 따로 계산하는 부분을 찾지 못했습니다. 그 이후 lifespan은 계산하는 것은 어느 부분을 확인해야 될까요?

감사합니다.

**Comment by erlim** [comment]
https://github.com/ESOS-Lab/AndroTrace/blob/master/kernel/nexus5_3.4.0/fs/namei.c#L2874
do_unlinkat 함수가 호출되는 시점을 delete time으로 보고 lifespan을 구했던 것 같습니다.

수집/분석 전에, 아래 내용이 보장 되는지 한번 더 확인해보시는게 좋을 것 같습니다.

https://man7.org/linux/man-pages/man2/unlink.2.html
 _"If the name was the last link to a file but any processes still have the file open, the file will remain in existence until the last file descriptor referring to it is closed."_

**Comment by hyunW3** [comment]
답변 감사합니다. 
https://github.com/ESOS-Lab/AndroTrace/blob/68e3f041bfeb484cc5a57fc4ee978d25bc60991b/kernel/g4_f500s/androtrace/androtrace.c#L452-L474
-> do_unlinkat 함수에서 androtrace_add_filels 함수를 호출하는데, lifespan를 구하는 부분이 주석처리되어있습니다.
https://github.com/ESOS-Lab/AndroTrace/blob/68e3f041bfeb484cc5a57fc4ee978d25bc60991b/kernel/g4_f500s/androtrace/parser/trace_parser.c#L190-L207
-> trace_parse.c에서 filels_parser()함수를 확인해보면 위와 같이 파싱하는 부분이 주석처리되어있습니다. 
만약 unlinkat 에서 androtrace_add_filels 를 호출하여 file의 lifespan을 구하려고 한다면, 주석 처리된 부분을 주석 처리하면 안 될 것 같아서 질문 드립니다.

**Comment by erlim** [comment]
당시, lifespan 정보는 상세 분석 대상이 아니었어서 commit 당시 주석처리 된것으로 보입니다.
주석은 풀고 확인하시면 됩니다 :)

**Comment by hyunW3** [comment]
감사합니다:)
