### ISSUE TITLE
code for server side

### ISSUE THREAD

**Issue by hyunW3** [ESOS-Lab/AndroTrace#2]
Since Androtrace is client-server model, client code and server code are both needed.
However, it doesn't consist server side code. Is it available?

**Comment by erlim** [comment]
Thank you for being interested in Androtrace. Unfortunately, we do not provide server-side code. 
Database schema depends on the requirement of what to be collected and analyzed for each research.

The following code describes the trace data structure.
I believe you could modify it for your research purpose and set up DBMS on the server side. 
https://github.com/ESOS-Lab/AndroTrace/blob/master/kernel/nexus5_3.4.0/androtrace/androtrace_define.h

_#Referneces:_ 
- Compose and collecting traces:
https://github.com/ESOS-Lab/AndroTrace/blob/master/kernel/nexus5_3.4.0/androtrace/androtrace.c#L133
- Local trace data parser:
https://github.com/ESOS-Lab/AndroTrace/blob/master/kernel/nexus5_3.4.0/androtrace/parser/trace_parser.c
- Android application that sends traces to the server: 
https://github.com/ESOS-Lab/AndroTrace/tree/master/transfer/app

**Comment by hyunW3** [comment]
Thank you
